/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectbanksystem;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author nakka
 */
public class Main extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        pack();
        
        Calendar cal = Calendar.getInstance();
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        int minute = cal.get(Calendar.MINUTE);
        int second = cal.get(Calendar.SECOND);
        int delay = 1000;
        // Update the time on the label
        jLabel2.setText(String.format("%02d:%02d:%02d", hour, minute, second));
        
        
        ActionListener updateClockAction = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Get the current time
                Calendar cal = Calendar.getInstance();
                int hour = cal.get(Calendar.HOUR_OF_DAY);
                int minute = cal.get(Calendar.MINUTE);
                int second = cal.get(Calendar.SECOND);

                // Update the time on the label
                jLabel2.setText(String.format("%02d:%02d:%02d", hour, minute, second));
            }
        };
        Timer timer = new Timer(delay, updateClockAction);
        timer.start();
        
    }
    final Color Y = new Color(255,254,171);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBorder1 = new Swing.PanelBorder();
        labelRecord = new javax.swing.JLabel();
        labelWithdraw = new javax.swing.JLabel();
        labelDeposit = new javax.swing.JLabel();
        labelAccount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(985, 522));

        jPanel1.setBackground(new java.awt.Color(14, 36, 32));
        jPanel1.setMinimumSize(new java.awt.Dimension(841, 384));

        panelBorder1.setBackground(new java.awt.Color(39, 89, 71));

        labelRecord.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelRecord.setForeground(new java.awt.Color(255, 255, 255));
        labelRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/record button.png"))); // NOI18N
        labelRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRecordMouseExited(evt);
            }
        });

        labelWithdraw.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        labelWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/withdraw button.png"))); // NOI18N
        labelWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelWithdrawMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelWithdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelWithdrawMouseExited(evt);
            }
        });

        labelDeposit.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelDeposit.setForeground(new java.awt.Color(255, 255, 255));
        labelDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/deposit button.png"))); // NOI18N
        labelDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDepositMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDepositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDepositMouseExited(evt);
            }
        });

        labelAccount.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labelAccount.setForeground(new java.awt.Color(255, 255, 255));
        labelAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account button.png"))); // NOI18N
        labelAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAccountMouseExited(evt);
            }
        });

        panelBorder1.setLayer(labelRecord, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(labelWithdraw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(labelDeposit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(labelAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAccount)
                    .addComponent(labelDeposit)
                    .addComponent(labelWithdraw)
                    .addComponent(labelRecord))
                .addGap(32, 32, 32))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelAccount)
                .addGap(32, 32, 32)
                .addComponent(labelDeposit)
                .addGap(32, 32, 32)
                .addComponent(labelWithdraw)
                .addGap(32, 32, 32)
                .addComponent(labelRecord)
                .addGap(32, 32, 32))
        );

        jPanel3.setBackground(new java.awt.Color(39, 89, 71));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank.png"))); // NOI18N
        jLabel4.setText(" Bank System Main Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gross-dark-cross 1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 168)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLOCK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseClicked
        // TODO add your handling code here:
        RegisterPage registerpage = new RegisterPage();
        registerpage.setVisible(true);
        dispose();
//        registerpage.setLocationRelativeTo(null);
//        registerpage.pack();
    }//GEN-LAST:event_labelAccountMouseClicked

    private void labelDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDepositMouseClicked
        // TODO add your handling code here:
        Deposit dp = new Deposit();
        dp.setVisible(true);
        dispose();
//        dp.setLocationRelativeTo(null);
//        dp.pack();
    }//GEN-LAST:event_labelDepositMouseClicked

    private void labelWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelWithdrawMouseClicked
        // TODO add your handling code here:
        Withdraw wd = new Withdraw();
        wd.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelWithdrawMouseClicked

    private void labelRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecordMouseClicked
        // TODO add your handling code here:
        RecordPage rp = new RecordPage();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelRecordMouseClicked

    private void labelAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseEntered
        // TODO add your handling code here:
        labelAccount.setForeground(Y);
    }//GEN-LAST:event_labelAccountMouseEntered

    private void labelAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAccountMouseExited
        // TODO add your handling code here:
        labelAccount.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelAccountMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void labelDepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDepositMouseEntered
        // TODO add your handling code here:
        labelDeposit.setForeground(Y);
    }//GEN-LAST:event_labelDepositMouseEntered

    private void labelDepositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDepositMouseExited
        // TODO add your handling code here:
        labelDeposit.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelDepositMouseExited

    private void labelWithdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelWithdrawMouseEntered
        // TODO add your handling code here:
        labelWithdraw.setForeground(Y);
    }//GEN-LAST:event_labelWithdrawMouseEntered

    private void labelWithdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelWithdrawMouseExited
        // TODO add your handling code here:
        labelWithdraw.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelWithdrawMouseExited

    private void labelRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecordMouseEntered
        // TODO add your handling code here:
        labelRecord.setForeground(Y);
    }//GEN-LAST:event_labelRecordMouseEntered

    private void labelRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecordMouseExited
        // TODO add your handling code here:
        labelRecord.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelRecordMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAccount;
    private javax.swing.JLabel labelDeposit;
    private javax.swing.JLabel labelRecord;
    private javax.swing.JLabel labelWithdraw;
    private Swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
