/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectbanksystem;

import java.io.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author nakka
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        setLocationRelativeTo(null);
        pack();
        
//        JOptionPane.showMessageDialog(null, "1. load first before proceed"
//                + "\n" + "2. don't forget to save before going out");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelBorder1 = new Swing.PanelBorder();
        btnCreate = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        panelBorder2 = new Swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        labelAmount1 = new javax.swing.JLabel();
        txtDigit = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(14, 36, 32));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Back");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        panelBorder1.setBackground(new java.awt.Color(39, 89, 71));

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtAmount.setColumns(16);
        txtAmount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtAddress.setColumns(16);
        txtAddress.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtName.setColumns(16);
        txtName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");

        labelAmount.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelAmount.setForeground(new java.awt.Color(255, 255, 255));
        labelAmount.setText("Amount");

        panelBorder1.setLayer(btnCreate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(txtAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(txtAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder1.setLayer(labelAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreate)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(labelAmount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(38, 38, 38)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelAmount))
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panelBorder2.setBackground(new java.awt.Color(39, 89, 71));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        labelAmount1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelAmount1.setForeground(new java.awt.Color(255, 255, 255));
        labelAmount1.setText("Digit");

        txtDigit.setColumns(16);
        txtDigit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnShow.setBackground(new java.awt.Color(0, 0, 0));
        btnShow.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        panelBorder2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder2.setLayer(labelAmount1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder2.setLayer(txtDigit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder2.setLayer(btnShow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelBorder2.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(labelAmount1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDigit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)))
                .addGap(32, 32, 32))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDigit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAmount1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel8.setBackground(new java.awt.Color(39, 89, 71));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bank.png"))); // NOI18N
        jLabel12.setText(" Bank System Account");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gross-dark-cross 1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Save");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Load");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addGap(8, 8, 8))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(862, 862, 862)))
                .addGap(32, 32, 32))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    HashMap<String, Account> hashAccount = new HashMap<>();
    private int nextAccountNumber = 1;
    private List<TransactionRecord> transactionRecords = new ArrayList<>();
    protected File lastLoadedFile;
//    TransactionRecord transactionRecords;


    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try{
        String name = txtName.getText();
        String address = txtAddress.getText();
        double balance = Double.parseDouble(txtAmount.getText());
        
        String digitCreated = String.valueOf(nextAccountNumber);
        Account account = new Account(name, address, balance);
        hashAccount.put(digitCreated, account);
        JOptionPane.showMessageDialog(null, "Account number: "
                + digitCreated + "\n" + account.information());
        
        
//-------------RECORDER CODE-------------------------------------------------------------------------------------------------------------------


        String transactionType = "   Register  ";
        LocalDate transactionDate = LocalDate.now();
        TransactionRecord record = new TransactionRecord(transactionType, transactionDate, nextAccountNumber,balance);
        addTransactionRecord(record);
        
        
//---------------------------------------------------------------------------------------------------------------------------------------------
        nextAccountNumber++;
//        showRecord(txtArea);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please, fill account information");
        } 
    }//GEN-LAST:event_btnCreateActionPerformed

    public void showRecord (JTextArea txtArea){
        try{
            txtArea.setText("no|  Transactions  |    Date   |  amount  |");
        for (TransactionRecord transactionRecord : transactionRecords) {
            String recordString = String.format(" %d | %-10s | %-12s | %,.2f%n",
                    transactionRecord.getTransactionNumber(),
                    transactionRecord.getTransactionType(), 
                    transactionRecord.getTransactionDate(), 
                    transactionRecord.getTransactionAmount());
            txtArea.append(recordString);
        }}catch (NullPointerException e){JOptionPane.showMessageDialog(null, "ERROR "+e);}
    }
    
    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        try {
            int accountNNumber = Integer.parseInt(txtDigit.getText());
            Account account = hashAccount.get(txtDigit.getText());
            txtArea.setText(account.information());
        } catch( NumberFormatException e ){
            JOptionPane.showMessageDialog(null, "Please, fill account digit number");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Account not found");
        } 
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        //Create object 
        try{
        int accountNumber = Integer.parseInt(txtDigit.getText());
        Account account = hashAccount.get(txtDigit.getText());
        double amount = account.balance;
        hashAccount.remove(txtDigit.getText());
        JOptionPane.showMessageDialog(null,
                "account number : " + txtDigit.getText()
                + "\n" + account.information() + "\n removed!");
        
        
        String transactionType = "CLOSE";
        LocalDate transactionDate = LocalDate.now();
        TransactionRecord record = new TransactionRecord(transactionType, transactionDate, accountNumber ,amount);
        addTransactionRecord(record);
        } catch( NumberFormatException e ){
            JOptionPane.showMessageDialog(null, "Please, fill account digit number");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Account not found");
        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        saveFileLocation(lastLoadedFile);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    
    
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        saveAccounts();
        JOptionPane.showMessageDialog(null, "Saved data!");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        loadAccounts();
        JOptionPane.showMessageDialog(null, "Load data!");
    }//GEN-LAST:event_jLabel15MouseClicked

    public void addTransactionRecord(TransactionRecord record) {
        transactionRecords.add(record);
    }

//    public List<TransactionRecord> getAllTransactionRecords() {
//        return transactionRecords;
//    }
    
    //-----------------------------------------------LOAD AND SAVE V1----------------------------

//    private void saveAccounts() {
//        try {
//            FileOutputStream fos = new FileOutputStream("accounts.dat");
//            ObjectOutputStream oos = new ObjectOutputStream(fos);
//            AccountData data = new AccountData(hashAccount, nextAccountNumber, transactionRecords);
//            oos.writeObject(data);
//            oos.close();
//            fos.close();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//
//    private void loadAccounts() {
//        try {
//            FileInputStream fis = new FileInputStream("accounts.dat");
//            ObjectInputStream ois = new ObjectInputStream(fis);
//
//            AccountData data = (AccountData) ois.readObject();
//            hashAccount = data.getAccounts();
//            nextAccountNumber = data.getNextAccountNumber();
//            transactionRecords = data.getTransactionRecords();
//
//            ois.close();
//            fis.close();
//        } catch (IOException | ClassNotFoundException e) {
//            e.printStackTrace();
//        }
//    }

     //-----------------------------------------------LOAD AND SAVE V1----------------------------
    
    
    //load and save v2
    
    private void saveAccounts() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null); // Show save dialog

        if (result == JFileChooser.APPROVE_OPTION) { // If "Save" button is clicked
            File file = fileChooser.getSelectedFile(); // Get selected file
            try {
                // create an output stream for writing to the selected file
                FileOutputStream fos = new FileOutputStream(file);
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                AccountData data = new AccountData(hashAccount, nextAccountNumber, transactionRecords);
                oos.writeObject(data); // Write data to file
                oos.close();
                fos.close();
                lastLoadedFile = file;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void loadAccounts() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null); // Show open dialog

        if (result == JFileChooser.APPROVE_OPTION) { // If "Open" button is clicked
            File file = fileChooser.getSelectedFile(); // Get selected file
            saveFileLocation(file);
            try {
                FileInputStream fis = new FileInputStream(file);
                ObjectInputStream ois = new ObjectInputStream(fis);
                AccountData data = (AccountData) ois.readObject();
                hashAccount = data.getAccounts();
                nextAccountNumber = data.getNextAccountNumber();
                transactionRecords = data.getTransactionRecords();
                ois.close();
                fis.close();
                lastLoadedFile = file;
//                saveFileLocation(lastLoadedFile);
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void saveFileLocation(File lastedLoadedFile){
        try {
            FileLocationSaver fileLocation = new FileLocationSaver(lastedLoadedFile);
            FileOutputStream fos = new FileOutputStream("fileLocation.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(fileLocation);
            oos.close();
            fos.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void loadFileLocation() {
        try {
            FileInputStream fis = new FileInputStream("fileLocation.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            FileLocationSaver fileLocation = (FileLocationSaver) ois.readObject();
            lastLoadedFile = fileLocation.getLastedLoadedFile();
            ois.close();
            fis.close();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    
    //load and save v2
    
    /**
     * @param args the command line arguments
     */

//        ImageIcon icon = new ImageIcon("bankicon.jpg");
//
//    // Get the image from the icon
//    Image image = icon.getImage();
//
//    // Scale the image to a new size
//    Image scaledImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
//
//    // Create a new icon from the scaled image
//    ImageIcon scaledIcon = new ImageIcon(scaledImage);
//
//    // Set the new icon to the label
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelAmount1;
    private Swing.PanelBorder panelBorder1;
    private Swing.PanelBorder panelBorder2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDigit;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
